/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PlotsInSohnaRouteImport } from './routes/plots-in-sohna'
import { Route as PlotsInJhajjarRouteImport } from './routes/plots-in-jhajjar'
import { Route as PlotsInGurgaonRouteImport } from './routes/plots-in-gurgaon'
import { Route as PlotsRouteImport } from './routes/plots'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlotsIndexRouteImport } from './routes/plots.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as PlotsSlugRouteImport } from './routes/plots.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlotsInSohnaRoute = PlotsInSohnaRouteImport.update({
  id: '/plots-in-sohna',
  path: '/plots-in-sohna',
  getParentRoute: () => rootRouteImport,
} as any)
const PlotsInJhajjarRoute = PlotsInJhajjarRouteImport.update({
  id: '/plots-in-jhajjar',
  path: '/plots-in-jhajjar',
  getParentRoute: () => rootRouteImport,
} as any)
const PlotsInGurgaonRoute = PlotsInGurgaonRouteImport.update({
  id: '/plots-in-gurgaon',
  path: '/plots-in-gurgaon',
  getParentRoute: () => rootRouteImport,
} as any)
const PlotsRoute = PlotsRouteImport.update({
  id: '/plots',
  path: '/plots',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlotsIndexRoute = PlotsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlotsRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlotsSlugRoute = PlotsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PlotsRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/plots': typeof PlotsRouteWithChildren
  '/plots-in-gurgaon': typeof PlotsInGurgaonRoute
  '/plots-in-jhajjar': typeof PlotsInJhajjarRoute
  '/plots-in-sohna': typeof PlotsInSohnaRoute
  '/privacy': typeof PrivacyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/plots/$slug': typeof PlotsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/plots/': typeof PlotsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/plots-in-gurgaon': typeof PlotsInGurgaonRoute
  '/plots-in-jhajjar': typeof PlotsInJhajjarRoute
  '/plots-in-sohna': typeof PlotsInSohnaRoute
  '/privacy': typeof PrivacyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/plots/$slug': typeof PlotsSlugRoute
  '/blog': typeof BlogIndexRoute
  '/plots': typeof PlotsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/plots': typeof PlotsRouteWithChildren
  '/plots-in-gurgaon': typeof PlotsInGurgaonRoute
  '/plots-in-jhajjar': typeof PlotsInJhajjarRoute
  '/plots-in-sohna': typeof PlotsInSohnaRoute
  '/privacy': typeof PrivacyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/plots/$slug': typeof PlotsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/plots/': typeof PlotsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/plots'
    | '/plots-in-gurgaon'
    | '/plots-in-jhajjar'
    | '/plots-in-sohna'
    | '/privacy'
    | '/blog/$slug'
    | '/plots/$slug'
    | '/blog/'
    | '/plots/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/plots-in-gurgaon'
    | '/plots-in-jhajjar'
    | '/plots-in-sohna'
    | '/privacy'
    | '/blog/$slug'
    | '/plots/$slug'
    | '/blog'
    | '/plots'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/plots'
    | '/plots-in-gurgaon'
    | '/plots-in-jhajjar'
    | '/plots-in-sohna'
    | '/privacy'
    | '/blog/$slug'
    | '/plots/$slug'
    | '/blog/'
    | '/plots/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  PlotsRoute: typeof PlotsRouteWithChildren
  PlotsInGurgaonRoute: typeof PlotsInGurgaonRoute
  PlotsInJhajjarRoute: typeof PlotsInJhajjarRoute
  PlotsInSohnaRoute: typeof PlotsInSohnaRoute
  PrivacyRoute: typeof PrivacyRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plots-in-sohna': {
      id: '/plots-in-sohna'
      path: '/plots-in-sohna'
      fullPath: '/plots-in-sohna'
      preLoaderRoute: typeof PlotsInSohnaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plots-in-jhajjar': {
      id: '/plots-in-jhajjar'
      path: '/plots-in-jhajjar'
      fullPath: '/plots-in-jhajjar'
      preLoaderRoute: typeof PlotsInJhajjarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plots-in-gurgaon': {
      id: '/plots-in-gurgaon'
      path: '/plots-in-gurgaon'
      fullPath: '/plots-in-gurgaon'
      preLoaderRoute: typeof PlotsInGurgaonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plots': {
      id: '/plots'
      path: '/plots'
      fullPath: '/plots'
      preLoaderRoute: typeof PlotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plots/': {
      id: '/plots/'
      path: '/'
      fullPath: '/plots/'
      preLoaderRoute: typeof PlotsIndexRouteImport
      parentRoute: typeof PlotsRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plots/$slug': {
      id: '/plots/$slug'
      path: '/$slug'
      fullPath: '/plots/$slug'
      preLoaderRoute: typeof PlotsSlugRouteImport
      parentRoute: typeof PlotsRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PlotsRouteChildren {
  PlotsSlugRoute: typeof PlotsSlugRoute
  PlotsIndexRoute: typeof PlotsIndexRoute
}

const PlotsRouteChildren: PlotsRouteChildren = {
  PlotsSlugRoute: PlotsSlugRoute,
  PlotsIndexRoute: PlotsIndexRoute,
}

const PlotsRouteWithChildren = PlotsRoute._addFileChildren(PlotsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  PlotsRoute: PlotsRouteWithChildren,
  PlotsInGurgaonRoute: PlotsInGurgaonRoute,
  PlotsInJhajjarRoute: PlotsInJhajjarRoute,
  PlotsInSohnaRoute: PlotsInSohnaRoute,
  PrivacyRoute: PrivacyRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
